name: Fetch from Garnix
on:
  check_suite:
    types: [completed]

jobs:
  verifyReproducible:
    name: Fetch Garnix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
      - run: |
          # This will timeout when flake is not built on Garnix
          nix build --no-update-lock-file --print-build-logs --print-out-paths '.#packages.x86_64-linux.hello-garnix'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact.outputs.filename }}-from-garnix
          path: ./result/*
